### ISSUE TITLE
Not all the withdrawal methods supported.

### ISSUE THREAD

**Issue by arjundvn24** [OfficialCSGOEmpire/API-Docs#6]
Hey after using your API for a few weeks, I and I am sure thousands of other developers out there feel the need to have Cryptocurrience withdrawals in the API as well. This helps us code our app to successfully conduct more trades hence increasing the Transaction on csgoempire and hence better funds for more development of csgoempire API further on. Please have a genuine and deep look into the reason why it wasn't implemented in the first time.

**Comment by arjundvn** [comment]
I develop scripts in order to facilitate myself for trading but it hurts the fact their exist no withdrawal method just like other csgo trading websites have.
![image](https://user-images.githubusercontent.com/72293696/175083085-19d46758-93d5-48ec-a68b-66c3b0f9291f.png)

![image](https://user-images.githubusercontent.com/72293696/175083295-f5f3bee6-7fc8-4bda-9cba-4ea6d401bd35.png)
.

**Comment by Art-em1s** [comment]
In order to protect our users against automated phishing/scamming attempts the following transactions **will never be supported via API keys**:

- Crypto withdrawals
- Tipping
- Wagering

Whilst we appreciate this may be a little annoying, security isn't something we're willing to compromise on in this instance.

This isn't an oversight, it's an intentional design choice.
